version: 2.1
jobs:
  lint_and_check:
    docker:
      - image: circleci/golang:1.18.1
    working_directory: /go/src/github.com/gballet/go-verkle

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache
            - srs-precomp

      - run: wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

      - run:
          name: Lint
          command: ./bin/golangci-lint run

        #- run: go get honnef.co/go/tools/cmd/staticcheck

      - run:
          name: Run the static checkers
          command: go vet
            #   /go/bin/staticcheck

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - save_cache: # Save the precomputed data in the cache
          key: srs-precomp
          paths:
            - "./precomp"

  test_linux:
    docker:
      - image: circleci/golang:1.18.1
    working_directory: /go/src/github.com/gballet/go-verkle

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache
            - srs-precomp

      - run:
          name: Run unit tests
          command: go test -v -coverprofile=coverage.txt -covermode=count ./...

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - save_cache: # Save the precomputed data in the cache
          key: srs-precomp
          paths:
            - "./precomp"

  test_linux_arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

    steps:
      - checkout

      - run:
          name: Run unit tests
          command: go test ./...

workflows:
  lint_and_test:
    jobs:
      - lint_and_check
      - test_linux
      - test_linux_arm
